import { connect } from 'react-redux'
import { Chat, Home as TargetComponent } from '../component'
import { navigate } from '../../Navigation'

const chats: Chat[] = [
  {
    icon: 'https://static1.cbrimages.com/wordpress/wp-content/uploads/2019/09/One-Piece-Monkey-D.-Luffy-Cropped.jpg?q=50&fit=contain&w=1140&h=&dpr=1.5',
    lastMessageAt: '2024-02-29T06:48:18.027Z',
    lastMessage: "i'm gonna be the king of the pirates",
    name: 'Monkey D. Luffy',
    notificationCount: 3,
    read: false,
    status: 'online',
  },
  {
    icon: 'https://i.pinimg.com/736x/d5/ec/fc/d5ecfcebb8c23952e964360c0841b8c3.jpg',
    lastMessageAt: '2024-02-18T06:48:18.027Z',
    lastMessage: 'im the strongest in this universe and all other universes. its because I train a lot',
    name: 'Goku',
    notificationCount: 0,
    read: true,
    status: 'recently-online',
  },
  {
    icon: 'https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/68b3ce3993df078213088ff88531be5f.jpe',
    lastMessageAt: '2024-02-27T06:48:18.027Z',
    lastMessage: 'this mihawk character will be a challenge.',
    name: 'Himura Kenshin',
    notificationCount: 0,
    read: true,
    status: 'online',
  },
  {
    icon: 'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2021/07/dragon-ball-majin-vegeta-super-saiyan-3-totalmente-oficial-fue-creado-toyotaro-2415529.jpg',
    lastMessageAt: '2024-02-27T06:48:18.027Z',
    lastMessage: 'you fool look at my message. I am the prince of all saiyans.',
    name: 'Prince Vegeta',
    notificationCount: 5,
    read: false,
    status: 'offline',
  },
  {
    icon: 'https://wallpapers-clan.com/wp-content/uploads/2022/08/zoro-pfp-15.jpg',
    lastMessageAt: '2024-02-26T08:48:18.027Z',
    lastMessage: 'im gonna sleep.',
    name: 'Roronoa Zoro',
    notificationCount: 0,
    read: true,
    status: 'recently-online',
  },
  {
    icon: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJt1T7OiCHm55Yi3kyDtkBcXmz7j_1x2vokERB2RudqI4RO2pcSh3u3UwoOUA9aavq4hg&usqp=CAU',
    lastMessageAt: '2024-02-27T06:48:18.027Z',
    lastMessage: 'im cooking up something good so get hungry',
    name: 'Vinsmoke Sanji',
    notificationCount: 0,
    read: true,
    status: 'online',
  },
  {
    icon: 'https://static1.thegamerimages.com/wordpress/wp-content/uploads/2021/02/killua-wink.jpg',
    lastMessageAt: '2024-02-27T06:48:18.027Z',
    lastMessage: 'hope gon is doing ok. I have not heard from him in a while ever since he went off with his dad.',
    name: 'Killua Zoldyck',
    notificationCount: 0,
    read: true,
    status: 'offline',
  },
  {
    icon: 'https://static.wikia.nocookie.net/fma/images/a/a8/Avatar_roy2003.png/revision/latest/scale-to-width/360?cb=20171026204538',
    lastMessageAt: '2024-02-21T12:00:45.027Z',
    lastMessage: 'you should pick up your pocket watch. Its a part of your identity from now.',
    name: 'Roy Mustang',
    notificationCount: 0,
    read: true,
    status: 'online',
  },
  {
    icon: 'https://i.pinimg.com/736x/8f/7a/fd/8f7afd2091611b04c1785896e089b4b2.jpg',
    lastMessageAt: '2024-02-20T19:24:38.027Z',
    lastMessage: 'I dont miss being a captain tbh',
    name: 'Yoruichi Shihouin',
    notificationCount: 0,
    read: true,
    status: 'offline',
  },
  {
    icon: 'https://archives.bulbagarden.net/media/upload/thumb/4/42/Gary_Oak_OS.png/220px-Gary_Oak_OS.png',
    lastMessageAt: '2024-02-19T16:22:22.027Z',
    lastMessage: 'lets just say Ash is lucky I gave up on being a pokemon master',
    name: 'Gary Oak',
    notificationCount: 0,
    read: true,
    status: 'recently-online',
  },
  {
    icon: 'https://static.wikia.nocookie.net/deathbattlefanon/images/7/7b/Levi_Ackerman.png/revision/latest?cb=20150303175453',
    lastMessageAt: '2024-02-16T01:01:02.027Z',
    lastMessage: 'so where did you say you saw the beast titan last?',
    name: 'Levi Ackerman',
    notificationCount: 0,
    read: true,
    status: 'recently-online',
  },
  {
    icon: 'https://miro.medium.com/v2/resize:fit:736/1*GHQ2nQfaZyF81STYtlmAyA.jpeg',
    lastMessageAt: '2024-02-07T06:48:18.027Z',
    lastMessage: 'maybe I will come back. the story is shaping up nice though',
    name: 'Suguru Geto',
    notificationCount: 0,
    read: true,
    status: 'offline',
  },
  {
    icon: 'https://static.wikia.nocookie.net/naruto/images/2/21/Profile_Jiraiya.PNG/revision/latest?cb=20160115173538',
    lastMessageAt: '2024-02-27T06:48:18.027Z',
    lastMessage: 'well they dont call me the toad sage for nothing.',
    name: 'Jiraiya',
    notificationCount: 0,
    read: true,
    status: 'online',
  },
]

const mapStateToProps = () => ({
  tags: ['all chats', 'fiends', 'family', 'co-workers', 'yatch club'],
  chats,
})

export const Home = connect(mapStateToProps, {})(TargetComponent)
